formatting:
  active: true
  autoCorrect: true
  NoWildcardImports:
    active: false
  Indentation:
    active: false
    indentSize: 2
  Filename:
    active: false
style:
  MagicNumber:
    active: false
  WildcardImport:
    active: false
  UnusedImports:
    active: true
complexity:
  LongMethod:
    threshold: 100
  LongParameterList:
    active: false
  TooManyFunctions:
    active: false
naming:
  FunctionNaming:
    active: true
    ignoreAnnotated:
      - 'Composable'
  TopLevelPropertyNaming:
    active: true
    propertyPattern: '(_)?[A-Za-z][A-Za-z0-9]*'
    constantPattern: '[A-Z][_A-Za-z0-9]*'

