formatting:
  active: true
  autoCorrect: true
  NoWildcardImports:
    active: false
  Indentation:
    active: false
    indentSize: 2
style:
  MagicNumber:
    active: false
  WildcardImport:
    active: false
complexity:
  LongMethod:
    threshold: 60

